spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: admin
    password: root
    url: jdbc:postgresql://localhost:5438/libraryDB

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: book-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.LongDeserializer

server:
  port: 8081

springdoc:
  swagger-ui:
    path: /swagger