spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: admin
    password: root
    url: jdbc:postgresql://localhost:5438/libraryDB

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true

  kafka:
    bootstrap-servers: kafka:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.LongSerializer

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger