spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: admin
    password: root
    url: jdbc:postgresql://localhost:5438/libraryDB

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger